// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX2AaDt_vKYutAHnp1zn3BfudqxMWmb6w',
    appId: '1:379492292508:web:6c3d22b4c94bcfab70da59',
    messagingSenderId: '379492292508',
    projectId: 'saveupapp',
    authDomain: 'saveupapp.firebaseapp.com',
    storageBucket: 'saveupapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPC2icrIdMZorAg3sC95ZbHojpHBmIsU',
    appId: '1:379492292508:android:2945113a73239ef970da59',
    messagingSenderId: '379492292508',
    projectId: 'saveupapp',
    storageBucket: 'saveupapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZcpAm08EHE0u0a13n7iXhGeu08VtmNw',
    appId: '1:379492292508:ios:c73b32eaec1a396a70da59',
    messagingSenderId: '379492292508',
    projectId: 'saveupapp',
    storageBucket: 'saveupapp.appspot.com',
    iosClientId: '379492292508-tj7vsh1fuj7gvoici1chmqirr7qn575m.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveup',
  );
}
